sensors:
  - type: BME680
    id: 1
    address: 0x76
    metrics:
      - metric: temperature
        poll: 20
        mqtt:
          topic: brompton/living-room/temperature
      - metric: humidity
        poll: 20
        mqtt:
          topic: brompton/living-room/humidity
      - metric: pressure
        poll: 60
        mqtt:
          topic: brompton/living-room/pressure
#      - metric: air_quality
#        poll: 900
#        mqtt:
#          topic: brompton/living-room/air_quality
leds:
  - type: rgb
    id: 1
    channels:
      r: 23
      g: 25
      b: 24
    notifications:
      allow:
        - after_sunrise
      deny:
        - after_sunset
    mqtt:
      topics:
        - topic: brompton/living-room/temperature
          colour:
            red: 0
            green: 255
            blue: 0
          style: flash
        - topic: brompton/living-room/humidity
          colour:
            red: 0
            green: 255
            blue: 0
          style: flash
        - topic: brompton/living-room/pressure
          colour:
            red: 0
            green: 255
            blue: 0
          style: flash

#  - type: BME280
#    id: 1
#    metrics:
#      - metric: temperature
#        unit: celsius
#        poll: 5
#      - metric: humidity
#        poll: 10
#      - metric: pressure
#        poll: 12
#  - type: DS18B20
#    id: 021583ad40ff
#
#  - type: bme680
#    id: test-id
#    metrics:
#      temperature:
#        poll: 5
#      humidity:
#        poll: 5
#      pressure:
#        poll: 5
#      air-quality:
#        poll: 60