sensors:
  - type: BME680
    id: 1
    active: true
    address: 0x76
    metrics:
      - metric: temperature
        poll: 20
        mqtt:
          topic: brompton/living-room/temperature
      - metric: humidity
        poll: 20
        mqtt:
          topic: brompton/living-room/humidity
      - metric: pressure
        poll: 60
        mqtt:
          topic: brompton/living-room/pressure

  - type: BME680
    id: 2
    active: true
    address: 0x77
    metrics:
      - metric: temperature
        poll: 20
        mqtt:
          topic: brompton/living-room-two/temperature
      - metric: humidity
        poll: 20
        mqtt:
          topic: brompton/living-room-two/humidity
      - metric: pressure
        poll: 60
        mqtt:
          topic: brompton/living-room-two/pressure
#      - metric: air_quality
#        poll: 900
#        mqtt:
#          topic: brompton/living-room/air_quality
leds:
  - type: rgb
    id: 1
    active: true
    channels:
      r: 23
      g: 8 # 25
      b: 24
    notifications:
      allow:
        - after_sunrise
      deny:
        - after_sunset
    mqtt:
      topics:
        - topic: brompton/living-room/temperature
          colour:
            red: 0
            green: 0
            blue: 255
          style: flash
        - topic: brompton/living-room/humidity
          colour:
            red: 0
            green: 0
            blue: 255
          style: flash
        - topic: brompton/living-room/pressure
          colour:
            red: 0
            green: 0
            blue: 255
          style: flash