sensors:
  - type: BME680
    id: 1
    address: 0x76
    metrics:
      - metric: temperature
        poll: 20
        mqtt:
          topic: brompton/living-room/temperature
      - metric: humidity
        poll: 20
        mqtt:
          topic: brompton/living-room/humidity
      - metric: pressure
        poll: 60
        mqtt:
          topic: brompton/living-room/pressure

  - type: BME680
    id: 2
    address: 0x77
    metrics:
      - metric: temperature
        poll: 20
        mqtt:
          topic: brompton/living-room-two/temperature
      - metric: humidity
        poll: 20
        mqtt:
          topic: brompton/living-room-two/humidity
      - metric: pressure
        poll: 60
        mqtt:
          topic: brompton/living-room-two/pressure
#      - metric: air_quality
#        poll: 900
#        mqtt:
#          topic: brompton/living-room/air_quality

  - type: DS18B20
    id: 3
    address: 021583a440ff
    metrics:
      - metric: temperature
        poll: 20
        mqtt:
          topic: brompton/living-room-three/temperature

  - type: DS18B20
    id: 4
    address: 021583ad40ff
    metrics:
      - metric: temperature
        poll: 20
        mqtt:
          topic: brompton/living-room-four/temperature

  - type: PMS5003
    id: 5
    address: /dev/ttyAMA0
    metrics:
      - metric: pm1.0
        poll: 60
        mqtt:
          topic: brompton/outside/particulate_matter/1.0
      - metric: pm2.5
        poll: 60
        mqtt:
          topic: brompton/outside/particulate_matter/2.5
      - metric: pm10.0
        poll: 60
        mqtt:
          topic: brompton/outside/particulate_matter/10.0